[tool.poetry]
name = "ga-demo"
version = "0.1.5"
description = ""
authors = ["Alex Vakhitov <alexius@hey.com>"]

[tool.poetry.dependencies]
python = "^3.10"
Django = "^4.1.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
